I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_1/d1s6c.rpy", line 166, in script
    show terry angry at left with dissolve
Exception: Image 'terry' does not accept attributes 'angry'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_1/d1s6c.rpy", line 166, in script
    show terry angry at left with dissolve
  File "/home/river/Downloads/renpy-8.2.0-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/home/river/Downloads/renpy-8.2.0-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/home/river/Downloads/renpy-8.2.0-sdk/renpy/exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/home/river/Downloads/renpy-8.2.0-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/home/river/Downloads/renpy-8.2.0-sdk/renpy/display/displayable.py", line 246, in _duplicate
    args.extraneous()
  File "/home/river/Downloads/renpy-8.2.0-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'terry' does not accept attributes 'angry'.

Linux-5.15.0-88-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.0.24012702
Rounded GUI 1.1.0
Sat Feb 10 13:38:48 2024
